remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: Computer Science Notes
tagline: Resources for computer science
description: Useful resources, notes etc. for computer science and other related subjects
